#!/bin/bash
# refactor me: something is still wrong here
RXB=0
TXB=0
for rxbytes in /sys/class/net/*/statistics/rx_bytes ; do
  let RXB+=$(< $rxbytes)
done
for txbytes in /sys/class/net/*/statistics/tx_bytes ; do
  let TXB+=$(< $txbytes)
done

sleep 2

RXBN=0
TXBN=0
for rxbytes in /sys/class/net/*/statistics/rx_bytes ; do
  let RXBN+=$(< $rxbytes)
done
for txbytes in /sys/class/net/*/statistics/tx_bytes ; do
  let TXBN+=$(< $txbytes)
done
#divide by two for the period, multiply by 10 to allow a correct decimal place
RXDIF=$(( (RXBN - RXB) * 5  ))
TXDIF=$(( (TXBN - TXB) * 5  ))

SPEEDU="^B/s"
SPEEDD="vB/s"
if [ $RXDIF -ge 10240 ]; then
    SPEEDD="vKi/s"
    RXDIF=$(( RXDIF / 10240 ))
fi

if [ $TXDIF -ge 10240 ]; then
    SPEEDU="vKi/s"
    TXDIF=$(( TXDIF / 10240 ))
fi

if [ $RXDIF -ge 10240 ]; then
    SPEEDD="vMi/s"
    RXDIF=$(( RXDIF / 10240 ))
fi

if [ $TXDIF -ge 10240 ]; then
    SPEEDU="vMi/s"
    TXDIF=$(( TXDIF / 10240 ))
fi

if [ $RXDIF -ge 10240 ]; then
    SPEEDD="vGi/s"
    RXDIF=$(( RXDIF / 10240 ))
fi

if [ $TXDIF -ge 10240 ]; then
    SPEEDU="vGi/s"
    TXDIF=$(( TXDIF / 10240 ))
fi

RXDIFF=$(( RXDIF % 10 ))
RXDIFI=$(( RXDIF / 10 ))
RXDIF="$RXDIFI"

if [ $RXDIFF -ne 0 ]; then
	RXDIF="$RXDIFI.$RXDIFF"
fi

TXDIFF=$(( TXDIF % 10 ))
TXDIFI=$(( TXDIF / 10 ))
TXDIF="$TXDIFI"

if [ $TXDIFF -ne 0 ]; then
	TXDIF="$TXDIFI.$TXDIFF"
fi


echo "$RXDIF $SPEEDD $TXDIF $SPEEDU"
